export type EventType = 'dsa' | 'war' | 'pr' | 'design' | 'tribunal';

export interface ActivityEvent {
  id: string;
  type: EventType;
  badge: string;
  dateStr: string; 
  timestamp: string; 
  title: string;
  desc: string;
  xp: number;
  stats: { label: string; value: string }[];
}

export const generateMockEvents = (): ActivityEvent[] => {
  const events: ActivityEvent[] = [];
  const now = new Date();
  
  // Dashboard Metrics:
  // - Current Streak: 5 Days (So today, yesterday, -2, -3, -4 must have events!)
  // - Total Events approx: 59 
  
  // 1. Explicit recent highlight events (Ensuring days 0, 1, 3, 4 are covered)
  events.push({
    id: 'evt-1',
    type: 'war',
    badge: 'badge-war',
    dateStr: 'TODAY, 14:32',
    timestamp: now.toISOString(),
    title: 'ENG-911: Survived Checkout Outage',
    desc: 'Successfully bypassed a massive Redis cache drop by manually shedding load on the database. Diagnosed the missing connection pool config in 4 minutes.',
    xp: 350,
    stats: [{ label: 'MTTR', value: '4m 12s' }, { label: 'CPU Usage Saved', value: '99% → 42%' }]
  });

  events.push({
    id: 'evt-2',
    type: 'dsa',
    badge: 'badge-dsa',
    dateStr: 'TODAY, 10:15',
    timestamp: new Date(now.getTime() - 4 * 3600000).toISOString(),
    title: 'ENG-402: Double-Billing Bug',
    desc: 'Traced the duplicate transaction ID in the Stripe webhook layer using a robust HashMap. Space complexity optimized.',
    xp: 150,
    stats: [{ label: 'Time Complexity', value: 'O(N)' }, { label: 'Tests', value: '24/24 Pass' }]
  });

  const yesterday = new Date(now.getTime() - 86400000);
  events.push({
    id: 'evt-3',
    type: 'pr',
    badge: 'badge-pr',
    dateStr: 'YESTERDAY, 18:40',
    timestamp: yesterday.toISOString(),
    title: 'ENG-128: Add Batching PR',
    desc: "Rejected junior engineer's PR. Caught a hidden memory leak generated by an unbounded .map() closure over database connections.",
    xp: 200,
    stats: [{ label: 'Vulnerabilities Prevented', value: '1' }, { label: 'Review Time', value: '8m' }]
  });

  events.push({
    id: 'evt-4',
    type: 'design',
    badge: 'badge-design',
    dateStr: 'YESTERDAY, 09:20',
    timestamp: new Date(yesterday.getTime() - 8 * 3600000).toISOString(),
    title: 'ENG-512: Global Rate Limiter',
    desc: 'Designed a fully stateless rate limiter utilizing Redis hashes and Lua scripts for atomic operations. Verified constraints under simulated load.',
    xp: 400,
    stats: [{ label: 'Architecture', value: 'Distributed' }, { label: 'Constraints Met', value: '5/5' }]
  });

  // Guarantee day -2 is covered to bridge the streak
  const twoDaysAgo = new Date(now.getTime() - 2 * 86400000);
  events.push({
    id: 'evt-streak-fix',
    type: 'pr',
    badge: 'badge-pr',
    dateStr: '2 DAYS AGO',
    timestamp: twoDaysAgo.toISOString(),
    title: 'ENG-108: Code Review',
    desc: 'Routine PR approval.',
    xp: 100,
    stats: []
  });

  const threeDaysAgo = new Date(now.getTime() - 3 * 86400000);
  events.push({
    id: 'evt-5',
    type: 'tribunal',
    badge: 'badge-error',
    dateStr: '3 DAYS AGO, 16:05',
    timestamp: threeDaysAgo.toISOString(),
    title: 'ENG-101: Refactor AuthManager',
    desc: 'Decoupled the AuthManager God Object using the Strategy pattern. Dropped Cyclomatic Complexity from 14 to 3 without breaking 42 legacy tests.',
    xp: 300,
    stats: [{ label: 'Complexity', value: '14 → 3' }, { label: 'Test Coverage', value: '100%' }]
  });

  const fourDaysAgo = new Date(now.getTime() - 4 * 86400000);
  events.push({
    id: 'evt-6',
    type: 'dsa',
    badge: 'badge-dsa',
    dateStr: '4 DAYS AGO, 11:30',
    timestamp: fourDaysAgo.toISOString(),
    title: 'ENG-405: Rate Limiter Window Overlap',
    desc: 'Replaced a flawed fixed-window API limiter with a Sliding Window Log. Prevented burst-bot exploitation.',
    xp: 150,
    stats: [{ label: 'Space Complexity', value: 'O(N)' }, { label: 'Execution', value: '12ms' }]
  });

  // 2. Generate exactly ~52 remaining historical challenges to align with 59 Total activities from the dashboard.
  // Instead of scattering them completely randomly, simulate natural human patterns:
  // Humans work in chunks. E.g. an intense 2 weeks of studying, a break, etc.
  const studyClusters = [12, 35, 60, 110]; // Days ago anchor points

  let idCounter = 7;
  for (const anchor of studyClusters) {
    // Generate 10-15 activities spanning roughly a week around each anchor point
    const clusterVolume = 12 + Math.floor(Math.random() * 4);
    for (let c = 0; c < clusterVolume; c++) {
      const daysAgo = anchor + Math.floor(Math.random() * 14) - 7;
      if (daysAgo <= 4) continue; // Don't overwrite our 5 day streak
      if (idCounter > 59) break;

      const evtDate = new Date(now.getTime() - daysAgo * 86400000);
      const mockTypes: EventType[] = ['dsa', 'dsa', 'pr', 'design']; // Bias towards DSA
      const type = mockTypes[Math.floor(Math.random() * mockTypes.length)];
      
      events.push({
        id: "hist-" + idCounter++,
        type,
        badge: 'badge-default',
        dateStr: daysAgo + ' DAYS AGO',
        timestamp: evtDate.toISOString(),
        title: "Historical " + type.toUpperCase() + " Practice",
        desc: 'Legacy historical activity.',
        xp: 50,
        stats: []
      });
    }
  }

  return events;
};

export const ACTIVITY_EVENTS = generateMockEvents();
