import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const targetPath = path.join(__dirname, '../lib/challenges.ts');
let fileContent = fs.readFileSync(targetPath, 'utf8');

// The script will generate 10 per type to add 50 total.
const types = [
  { t: 'DSA', badge: 'badge-dsa', levels: ['SDE I', 'SDE II', 'SDE III'] },
  { t: 'PR Review', badge: 'badge-pr', levels: ['SDE I', 'SDE II', 'SDE III'] },
  { t: 'War Room', badge: 'badge-war', levels: ['SDE II', 'SDE III'] },
  { t: 'System Design', badge: 'badge-design', levels: ['SDE II', 'SDE III'] },
  { t: 'Tech Debt Tribunal', badge: 'badge-error', levels: ['SDE II', 'SDE III'] }
];

const companies = ['Google', 'Meta', 'Amazon', 'Netflix', 'Stripe', 'Airbnb', 'Uber', 'Datadog', 'Notion', 'Figma'];
const statuses = ['Not Started', 'Completed', 'In Progress'];

let genCode = "";

let idCounter = 1000;

for (let cType of types) {
  for (let i = 0; i < 10; i++) {
    idCounter++;
    const comp1 = companies[Math.floor(Math.random() * companies.length)];
    let comp2 = companies[Math.floor(Math.random() * companies.length)];
    while(comp1 === comp2) comp2 = companies[Math.floor(Math.random() * companies.length)];

    const level = cType.levels[Math.floor(Math.random() * cType.levels.length)];
    const timeEst = `~${[15, 20, 30, 45, 60][Math.floor(Math.random() * 5)]} min`;
    const status = statuses[Math.floor(Math.random() * statuses.length)];

    genCode += `  ,\n  {
    id: 'ENG-${idCounter}',
    type: '${cType.t}',
    badgeClass: '${cType.badge}',
    title: 'Autogenerated Ticket - ${cType.t} ${i+1}',
    companies: ['${comp1}', '${comp2}'],
    timeEst: '${timeEst}',
    level: '${level}',
    status: '${status}',
    desc: 'This is an autogenerated challenge description for ${cType.t}. Real world scenarios would involve deep telemetry, bug reproduction steps, or whiteboard scalability logic. For now, solve the issue.'
  }`;
  }
}

// Find the last closing bracket of the array
const lastBracketIndex = fileContent.lastIndexOf('];');
if (lastBracketIndex !== -1) {
    const newContent = fileContent.slice(0, lastBracketIndex) + genCode + '\n];';
    fs.writeFileSync(targetPath, newContent);
    console.log("Successfully added 50 challenges.");
} else {
    console.error("Could not find the closing bracket.");
}
