import { Challenge } from './types';

export const warChallenges: Challenge[] = [
  {
    id: 'ENG-WAR-001',
    type: 'War Room',
    badgeClass: 'badge-war',
    title: '502 Bad Gateway Loop',
    companies: ['Cloudflare', 'Vercel'],
    timeEst: '~15 min',
    level: 'Junior',
    status: 'Not Started',
    desc: 'Nginx is throwing 502 Bad Gateway errors. You check the Node.js application server, and it is running. But logs show the Node process restarting every 5 seconds.',
    solution: 'The application is encountering a fatal uncaught exception during boot (e.g., failed DB connection string) and PM2/Docker is constantly restarting it. Fix the environment variable.',
    options: [
      { label: 'A', title: 'Restart the Nginx proxy', sub: 'sudo systemctl restart nginx', isCorrect: false },
      { label: 'B', title: 'Fix the bad environment variable causing boot crash', sub: 'Check .env, fix DB_URL, then pm2 restart app', isCorrect: true },
      { label: 'C', title: 'Scale out to 3 more pods', sub: 'kubectl scale deployment app --replicas=6', isCorrect: false },
      { label: 'D', title: 'Reboot the entire host machine', sub: 'sudo reboot', isCorrect: false },
    ]
  },
  {
    id: 'ENG-WAR-002',
    type: 'War Room',
    badgeClass: 'badge-war',
    title: 'Disk 100% Full (No Space Left on Device)',
    companies: ['AWS', 'DigitalOcean'],
    timeEst: '~15 min',
    level: 'Junior',
    status: 'Not Started',
    desc: 'The database server suddenly stopped accepting writes. `df -h` shows `/var/log` is at 100% capacity.',
    solution: 'Application debug logs were left on in production, and log rotation (logrotate) was not configured. Find the massive log file, truncate it (`> app.log`), and setup logrotate.',
    options: [
      { label: 'A', title: 'Reboot the database server', sub: 'sudo reboot', isCorrect: false },
      { label: 'B', title: 'Increase EBS volume size immediately', sub: 'aws ec2 modify-volume --size 500', isCorrect: false },
      { label: 'C', title: 'Truncate the giant log file and configure logrotate', sub: '> /var/log/app.log && nano /etc/logrotate.d/app', isCorrect: true },
      { label: 'D', title: 'Restart the Postgres service', sub: 'sudo systemctl restart postgresql', isCorrect: false },
    ]
  },
  {
    id: 'ENG-WAR-003',
    type: 'War Room',
    badgeClass: 'badge-war',
    title: 'Postgres Max Connections Exhausted',
    companies: ['Supabase', 'Heroku'],
    timeEst: '~25 min',
    level: 'Mid',
    status: 'Not Started',
    desc: 'Traffic spiked 3x. The API servers auto-scaled from 5 pods to 50 pods. Immediately after scaling, the entire platform went offline with "FATAL: sorry, too many clients already".',
    solution: 'Each new API pod opened its own pool of DB connections, exceeding Postgres\'s `max_connections` limit. Deploy a connection pooler like PgBouncer to multiplex connections.',
    options: [
      { label: 'A', title: 'Scale the API pods back down to 5', sub: 'kubectl scale deployment api --replicas=5', isCorrect: false },
      { label: 'B', title: 'Increase max_connections in postgresql.conf to 10,000', sub: 'ALTER SYSTEM SET max_connections = 10000;', isCorrect: false },
      { label: 'C', title: 'Deploy PgBouncer to multiplex all pod connections', sub: 'helm install pgbouncer bitnami/pgbouncer', isCorrect: true },
      { label: 'D', title: 'Restart the primary database', sub: 'sudo systemctl restart postgresql', isCorrect: false },
    ]
  },
  {
    id: 'ENG-WAR-004',
    type: 'War Room',
    badgeClass: 'badge-war',
    title: 'Kafka Poison Pill (Dead Letter Queue)',
    companies: ['Uber', 'DoorDash'],
    timeEst: '~30 min',
    level: 'Mid',
    status: 'Not Started',
    desc: 'The order-fulfillment microservice stopped processing new orders 2 hours ago. CPU is low. The consumer group lag is in the millions. A single malformed JSON message is at the head of the partition.',
    solution: 'The consumer crashes parsing the bad message, restarts, and pulls the exact same message again in an infinite loop. Manually advance the Kafka offset or implement a Dead Letter Queue (DLQ) for failed messages.',
    options: [
      { label: 'A', title: 'Restart the consumer service pods', sub: 'kubectl rollout restart deployment order-consumer', isCorrect: false },
      { label: 'B', title: 'Delete and recreate the Kafka topic', sub: 'kafka-topics.sh --delete --topic orders', isCorrect: false },
      { label: 'C', title: 'Increase consumer group instances to process lag faster', sub: 'kubectl scale deployment order-consumer --replicas=20', isCorrect: false },
      { label: 'D', title: 'Skip the bad message by advancing the offset, implement DLQ', sub: 'kafka-consumer-groups.sh --reset-offsets --to-offset +1', isCorrect: true },
    ]
  },
  {
    id: 'ENG-WAR-005',
    type: 'War Room',
    badgeClass: 'badge-war',
    title: 'ElasticSearch Split-Brain',
    companies: ['Datadog', 'Elastic'],
    timeEst: '~35 min',
    level: 'Senior',
    status: 'Not Started',
    desc: 'A brief network partition occurred between AZ1 and AZ2. Now, users are seeing completely different search results depending on which server processes their request. Data is diverging.',
    solution: 'The ES cluster experienced "Split Brain". Both halves elected a master node because `minimum_master_nodes` was misconfigured (not set to N/2 + 1). You must manually resolve data conflicts and restart nodes.',
    options: [
      { label: 'A', title: 'Add more ES data nodes to each AZ', sub: 'terraform apply -var es_node_count=10', isCorrect: false },
      { label: 'B', title: 'Set minimum_master_nodes = N/2+1, resolve conflicts, restart', sub: 'PUT /_cluster/settings { minimum_master_nodes: 2 }', isCorrect: true },
      { label: 'C', title: 'Restore both sides from yesterday\'s snapshot', sub: 'POST /_snapshot/backup/restore', isCorrect: false },
      { label: 'D', title: 'Increase the ES heap size on all nodes', sub: 'ES_JAVA_OPTS="-Xms8g -Xmx8g"', isCorrect: false },
    ]
  },
  {
    id: 'ENG-WAR-006',
    type: 'War Room',
    badgeClass: 'badge-war',
    title: 'Cascading Failure via Synchronous Calls',
    companies: ['Amazon', 'Netflix'],
    timeEst: '~30 min',
    level: 'Senior',
    status: 'Not Started',
    desc: 'The non-critical "Recommendations" service slowed down. Suddenly, the critical "Checkout" service crashed. Why did a minor service take down the core business?',
    solution: 'Checkout makes synchronous REST calls to Recommendations. Because it slowed down, Checkout threads blocked waiting for replies, exhausting thread pools. Implement the Circuit Breaker pattern.',
    options: [
      { label: 'A', title: 'Scale up the Recommendations service', sub: 'kubectl scale deployment recommendations --replicas=30', isCorrect: false },
      { label: 'B', title: 'Restart the Checkout service pods', sub: 'kubectl rollout restart deployment checkout', isCorrect: false },
      { label: 'C', title: 'Add a timeout + Circuit Breaker on Checkout → Recommendations calls', sub: 'Implement Resilience4j/Hystrix circuit breaker with 500ms timeout', isCorrect: true },
      { label: 'D', title: 'Move both services into a single monolith', sub: 'Consolidate to reduce network hops', isCorrect: false },
    ]
  },
  {
    id: 'ENG-WAR-007',
    type: 'War Room',
    badgeClass: 'badge-war',
    title: 'Expired SSL Certificate',
    companies: ['Twilio', 'Okta'],
    timeEst: '~10 min',
    level: 'Junior',
    status: 'Not Started',
    desc: 'At exactly 00:00 UTC, all iOS mobile apps failed to connect to the API with vague network errors. Web users see a red padlock.',
    solution: 'The wildcard SSL/TLS certificate expired. Jump into the load balancer/Certbot, renew the certificate, and restart the proxy layer.',
    options: [
      { label: 'A', title: 'Restart all API server pods', sub: 'kubectl rollout restart deployment api', isCorrect: false },
      { label: 'B', title: 'Roll back the last deployment', sub: 'kubectl rollout undo deployment api', isCorrect: false },
      { label: 'C', title: 'Renew the TLS certificate and reload the proxy', sub: 'certbot renew && sudo nginx -s reload', isCorrect: true },
      { label: 'D', title: 'Flush Cloudflare CDN cache globally', sub: 'cf purge --all-zones', isCorrect: false },
    ]
  },
  {
    id: 'ENG-WAR-008',
    type: 'War Room',
    badgeClass: 'badge-war',
    title: 'Replication Lag causing Stale Reads',
    companies: ['Meta', 'Instagram'],
    timeEst: '~20 min',
    level: 'Mid',
    status: 'Not Started',
    desc: 'Users are complaining that when they update their profile picture, it still shows the old picture on their feed immediately after saving.',
    solution: 'Writes go to the Primary DB, but Reads come from the Replica. Due to high load, replication lag is 2 seconds. Force reads to the Primary DB for the current user for 5 seconds after a write (Read-Your-Writes consistency).',
    options: [
      { label: 'A', title: 'Invalidate the CDN cache on every profile update', sub: 'cf purge --tag=profile-images', isCorrect: false },
      { label: 'B', title: 'Disable read replicas entirely and read from primary always', sub: 'DB_READ_HOST=$DB_PRIMARY_HOST', isCorrect: false },
      { label: 'C', title: 'After a write, force reads to the Primary for 5 seconds', sub: 'Set session flag: read_from_primary=true for 5s TTL', isCorrect: true },
      { label: 'D', title: 'Add more read replicas to reduce per-replica lag', sub: 'terraform apply -var replica_count=5', isCorrect: false },
    ]
  },
  {
    id: 'ENG-WAR-009',
    type: 'War Room',
    badgeClass: 'badge-war',
    title: 'OOM Killed (Memory Leak over time)',
    companies: ['Docker', 'Kubernetes'],
    timeEst: '~25 min',
    level: 'Mid',
    status: 'Not Started',
    desc: 'Every 24 hours, K8s kills the reporting pod with exit code 137. The memory graphs show a slow, perfect diagonal line climbing upward until death.',
    solution: 'Exit code 137 means Out Of Memory (OOMKilled). Use a heap snapshot profiler to find the array or global object that is growing indefinitely without being garbage collected.',
    options: [
      { label: 'A', title: 'Raise the pod memory limit to 16GB', sub: 'resources: limits: memory: 16Gi', isCorrect: false },
      { label: 'B', title: 'Add a daily cron job to restart the pod', sub: 'kubectl delete pod reporting-xxx (via CronJob)', isCorrect: false },
      { label: 'C', title: 'Use a heap profiler to find and fix the memory leak', sub: 'node --inspect app.js, capture heap snapshots over time', isCorrect: true },
      { label: 'D', title: 'Migrate the service to a serverless Lambda function', sub: 'serverless deploy --function reporting', isCorrect: false },
    ]
  },
  {
    id: 'ENG-WAR-010',
    type: 'War Room',
    badgeClass: 'badge-war',
    title: 'DNS Propagation Outage',
    companies: ['Shopify', 'Squarespace'],
    timeEst: '~20 min',
    level: 'Mid',
    status: 'Not Started',
    desc: 'We migrated our domain to a new AWS load balancer. 50% of global users can access the site, but the other 50% are hitting the old decommissioned IP address and timing out.',
    solution: 'The TTL (Time To Live) on the old DNS A-record was set to 48 hours instead of 5 minutes before the migration. You must temporarily turn the old server back on and proxy traffic to the new one while DNS propagates globally.',
    options: [
      { label: 'A', title: 'Flush DNS on all global Cloudflare edge nodes', sub: 'cf dns purge --all', isCorrect: false },
      { label: 'B', title: 'Force all users to refresh their browser cache', sub: 'Send a push notification to clear browser cache', isCorrect: false },
      { label: 'C', title: 'Bring old server back up and proxy it to new LB while DNS propagates', sub: 'Restart old EC2, configure nginx proxy_pass to new LB IP', isCorrect: true },
      { label: 'D', title: 'Roll back the DNS change entirely and stay on old server', sub: 'aws route53 change-resource-record-sets (revert)', isCorrect: false },
    ]
  },

];
