import type { Challenge } from '../types';
// ─── ENG-PR-012 ─────────────────────────────────────────────────────────────────

const challenge: Challenge = {
    id: 'ENG-PR-012',
    type: 'PR Review',
    badgeClass: 'badge-pr',
    title: 'Broken Unique Constraint — Race Condition in Registration',
    companies: ['Twitch', 'Discord'],
    timeEst: '~12 min',
    level: 'Junior',
    status: 'Not Started',
    desc: 'Users report duplicate accounts being created with the same email during load testing of the new registration flow. The code checks for existing emails before inserting — but under load, duplicates slip through. Find the flaw.',
    solution: 'The check-then-insert pattern is a classic TOCTOU (Time-of-Check-Time-of-Use) race condition. Two requests can both pass the SELECT check before either completes the INSERT. Fix: enforce uniqueness at the database level with a UNIQUE constraint on the email column and catch the unique violation error (PostgreSQL error code 23505) in the application. Application-level checks are for UX feedback only — never the authoritative guard.',
    prReview: {
        prNumber: 921,
        prBranch: 'feature/user-registration',
        prBase: 'main',
        prAuthor: 'junior-dev-99',
        prFile: 'src/routes/auth.ts',
        prAge: '2 days ago',
        background: 'A new self-serve registration flow replaces the invite-only system. Emails must be unique across the platform.',
        changes: 'Added a check that looks up the email before inserting. If a user with that email exists, a 409 Conflict is returned. Otherwise the user is created.',
        testing: 'Manual testing with the same email twice correctly returns 409 on the second attempt. Works in dev.',
        hints: [
            'Two simultaneous registration requests with the same email both hit the SELECT. What do they both see?',
            'Where is the only place that can atomically guarantee uniqueness for a database column?',
            'What PostgreSQL error code is thrown when a UNIQUE constraint is violated, and how would you catch it?',
        ],
        diff: [
            { lineNumL: 8, lineNumR: 8, type: 'normal', text: "  const { email, password } = req.body;" },
            { lineNumL: null, lineNumR: 9, type: 'addition', text: "  const existing = await db.query(" },
            { lineNumL: null, lineNumR: 10, type: 'addition', text: "    'SELECT id FROM users WHERE email = $1', [email]" },
            { lineNumL: null, lineNumR: 11, type: 'addition', text: "  );" },
            { lineNumL: null, lineNumR: 12, type: 'addition', text: "  if (existing.rows.length > 0) {" },
            { lineNumL: null, lineNumR: 13, type: 'addition', text: "    return res.status(409).json({ error: 'Email already registered' });" },
            { lineNumL: null, lineNumR: 14, type: 'addition', text: "  }" },
            { lineNumL: null, lineNumR: 15, type: 'addition', text: "  await db.query(" },
            { lineNumL: null, lineNumR: 16, type: 'addition', text: "    'INSERT INTO users (email, password) VALUES ($1, $2)', [email, hashedPw]" },
            { lineNumL: null, lineNumR: 17, type: 'addition', text: "  );" },
            { lineNumL: 9, lineNumR: 18, type: 'normal', text: "  res.status(201).json({ message: 'Account created' });" },
        ],
        bugOptions: [
            { value: 'toctou_race', label: 'TOCTOU race condition', sub: 'Check and insert are not atomic' },
            { value: 'plain_text_pw', label: 'Plaintext password', sub: 'Password not hashed before insert' },
            { value: 'sql_injection', label: 'SQL injection', sub: 'Inputs not parameterised' },
            { value: 'missing_tx', label: 'Missing transaction', sub: 'Insert not wrapped in a transaction' },
            { value: 'no_validation', label: 'No input validation', sub: 'Email format not validated' },
            { value: 'wrong_status', label: 'Wrong status code', sub: '409 should be a different code' },
        ],
        correctBugType: 'toctou_race',
        successExplanation: "Correct — this is a TOCTOU (Time-of-Check-Time-of-Use) race. Two concurrent requests both execute the SELECT before either runs the INSERT. Both see zero rows and proceed. Both insert. Duplicate account created. The only correct fix is a UNIQUE constraint at the database level (ALTER TABLE users ADD CONSTRAINT users_email_unique UNIQUE (email)) and catching error code 23505 in the catch block. The application-level check can stay for good UX, but it is never the authoritative guard.",
        failExplanation: "The bug is a TOCTOU race on lines 9–16. SELECT then INSERT is not atomic. Under load, two requests both pass the SELECT check before either commits the INSERT, resulting in duplicate rows. The fix is a DB-level UNIQUE constraint on users.email. In the catch block, test if (err.code === '23505') and return 409. Application-level checks are a UX convenience, not a data integrity guarantee — the database is the last line of defence.",
    },
};